---
test_name: Post an anonymous comment on an article
stages:
  - name: post
    request:
      url: http://localhost:5002/comments/new?id=14
      method: POST
      json:
        content: this is a comment
      headers:
        content-type: application/json
    response:
      status_code: 201
---
test_name: Post an authenticated comment on an article
stages:
  - name: post
    request:
      url: http://localhost:5002/comments/new?id=14
      method: POST
      auth:
        - ki9e
        - password
      json:
        content: this is a new comment
      headers:
        content-type: application/json
    response:
      status_code: 201
---
test_name: Check that comments on the article were returned in order
stages:
  - name: retrieve_comments
    request:
      url: http://localhost:5002/comments?id=14
      method: GET
      json:
        amount: 2
      headers:
        content-type: application/json
    response:
      status_code: 200
