---
test_name: attempt to post an article without authenticating
stages:
  - name: post
    request:
      url: http://localhost:5001/articles/new
      method: POST
      json:
        title: Test_article
        content: Lorem ipsum dolor sit amet.
      headers:
        content-type: application/json
    response:
      status_code: 401

---
test_name: attempt to post an article using the wrong password
stages:
  - name: post
    request:
      url: http://localhost:5001/articles/new
      method: POST
      auth:
        - ki12e
        - password1h
      json:
        title: Test_article
        content: Lorem ipsum dolor sit amet.
      headers:
        content-type: application/json
    response:
      status_code: 401

---
test_name: post an article successfully
stages:
  - name: post
    request:
      url: http://localhost:5001/articles/new
      method: POST
      auth:
        - ki12e
        - password1
      json:
        title: Test_article1
        content: Lorem ipsum dolor sit amet.
      headers:
        content-type: application/json
    response:
      status_code: 201

---
test_name: retrieve the newly posted article
stages:
  - name: post
    request:
      url: http://localhost:5001/articles/view/recent?amount=1
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200

---
test_name: check that the newly posted article is most recent
stages:
  - name: post
    request:
      url: http://localhost:5001/articles/view/recent?amount=3
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
