DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`author`	VARCHAR NOT NULL,
	`content`	VARCHAR NOT NULL,
	`date`	DATETIME NOT NULL,
	`articleid`	INTEGER NOT NULL
);
