DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	VARCHAR NOT NULL,
	`email`	VARCHAR NOT NULL UNIQUE,
	`password`	VARCHAR NOT NULL
);
